# Generated by Django 4.2.2 on 2023-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_role_name'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to='auth_user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
